INSERT INTO games (id, name, type, stock, price) VALUES (1, 'Crash Bandicoot', 'Xbox', 10, 59.99)
INSERT INTO games (id, name, type, stock, price) VALUES (2, 'Devil May Cry 5', 'PC', 15, 39.99)
INSERT INTO games (id, name, type, stock, price) VALUES (3, 'Evil Within', 'PS4', 12, 19.99)
INSERT INTO games (id, name, type, stock, price) VALUES (4, 'Forza Horizon 4', 'PS4', 20, 59.99)
INSERT INTO games (id, name, type, stock, price) VALUES (5, 'Prototype 2', 'Xbox', 17, 24.99)
INSERT INTO games (id, name, type, stock, price) VALUES (6, 'Torchlight 2', 'PC', 30, 9.99)
INSERT INTO games (id, name, type, stock, price) VALUES (6, 'World of Warcraft', 'PC', 40, 14.99)

INSERT INTO clients (id, first_name, last_name, birth_day) VALUES (1, 'Adam', 'Adamo', '1988-04-24')
INSERT INTO clients (id, first_name, last_name, birth_day) VALUES (2, 'Bart', 'Boom', '1992-03-15')
INSERT INTO clients (id, first_name, last_name, birth_day) VALUES (3, 'Didier', 'Dumbo', '1995-11-08')
INSERT INTO clients (id, first_name, last_name, birth_day) VALUES (4, 'Karel', 'Kont', '1986-05-21')
INSERT INTO clients (id, first_name, last_name, birth_day) VALUES (5, 'Ludo', 'Leip', '1996-08-11')
INSERT INTO clients (id, first_name, last_name, birth_day) VALUES (6, 'Maarten', 'Mormel', '1990-03-09')
INSERT INTO clients (id, first_name, last_name, birth_day) VALUES (7, 'Wesley', 'Jaemers', '1989-06-01')